prety formating

diff --git a/sanitazerdi b/sanitazerdi
--- a/sanitazerdi
+++ b/sanitazerdi
@@ -4,11 +4,11 @@ var="y"
 wd=${1:-"$(pwd)"}
 wd="${wd}/"
 echo "** Cleanning Folder Names **"
-read -r -p  "Sanitazing ""$wd"" Continue (n/Y): " ans
+read -r -p "Sanitazing ""$wd"" Continue (n/Y): " ans
 ans=${ans:-$var}
-if [ "$ans" != "$var" ];  then
-    echo "Terminado por el usuarion. Fail";
-    exit 1;
+if [ "$ans" != "$var" ]; then
+    echo "Terminado por el usuarion. Fail"
+    exit 1
 fi
 
 # Clean foldernames
@@ -16,9 +16,8 @@ fi
 (
 
     echo "** Cleanning Folder Names **"
-    find "$wd"  -ignore_readdir_race -depth -type d  -exec /home/anp/SRC/PERL/sanitazer/sanitazer13.pl '{}'  \;
+    find "$wd" -ignore_readdir_race -depth -type d -exec /home/anp/SRC/PERL/sanitazer/sanitazer13.pl '{}' \;
 )
 
 # the () prevent effects inmidialy after finishing
 #
-
